version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: yala_diary_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yala_diary
    ports:
      - "5432:5432"
    volumes:
      - yala_diary_pgdata:/var/lib/postgresql/data

volumes:
  yala_diary_pgdata:
